### PR TITLE
Add GitHub Actions CI.

### PR DESCRIPTION
**Pull request by XhmikosR**
@rvagg please register for GitHub Actions. This tests Ubuntu and Windows. I only test >= 8 BTW

### CODE REVIEW

**Comment by rvagg** [comment]
sweet! thanks

**Comment by XhmikosR** [comment]
@rvagg the lock file is needed for `npm ci`.

**Comment by rvagg** [comment]
ok, well I don't want a lock file, can't I just use `npm test`?

**Comment by XhmikosR** [comment]
Are you sure you don't want a lock file?

If so, I will change the patch.

**Comment by rvagg** [comment]
yes, I'm sure. package-lock.json is good if you're distributing an application, but for a library that applications depend on (or libraries depend on), you should let your dependencies float and it's then up to the upstream user(s) to determine via their test suite that the dependencies are working properly.

**Comment by XhmikosR** [comment]
Done, I'll disable the lock file in another PR.

**Comment by XhmikosR** [comment]
BTW due to the nature of the docker containers, tests don't fail on Windows CI, but they do locally for me.

Either way, with #4 it works fine for me.

**Pull request merged**
